---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/sonarr-config:/config
      - ./data:/data
      - /mnt/satapool/media:/media
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/radarr-config:/config
      - ./data:/data
      - /mnt/satapool/media:/media
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/lidarr-config:/config
      - ./data:/data
      - /mnt/satapool/media:/media
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/readarr-config:/config
      - ./data:/data
      - /mnt/satapool/media:/media
    ports:
      - "8787:8787"
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
    volumes:
      - ./config/mylar-config:/config
      - ./data:/data
      - /mnt/satapool/media:/media
    ports:
      - "8090:8090"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/prowlarr-config:/config
      - /mnt/satapool/media:/media
    ports:
      - "9696:9696"
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
      - JELLYFIN_TYPE=emby
    volumes:
      - ./config/jellyseerr-config:/config
      - /mnt/satapool/media:/media
    ports:
      - "5055:5055"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent-config:/config
      - ./data/torrents:/data/torrents
      - /mnt/satapool/media:/media
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    network_mode: "host"
    environment:
      - PUID=568
      - PGID=568
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/ombi-config:/config
      - /mnt/satapool/media:/media
    ports:
      - "3579:3579"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=13011
      - PGID=13000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ./config/sabnzbd-config:/config
      - /mnt/satapool/media:/media
      - ./data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped
